language: ruby
cache: bundler
os:
- linux
- osx
python:
- 2.7
rvm:
- 2.5
- 2.4
- 2.3
- ruby-head
before_install:
- gem install bundler -v 2.0.1
- bundle update
- pip install --user xml2rfc
- export PATH=$(python -c "import os,site; print os.path.join(site.USER_BASE, 'bin')"):$PATH
matrix:
  allow_failures:
    - rvm: ruby-head
