dist: trusty
sudo: true
language: ruby
python:
- 2.7
rvm:
  - 2.5
  - 2.4
  - 2.3
  - ruby-head

env:
  - DEV_MODE=true

addons:
  apt:
    packages:
    - python-lxml
    - python-pip

before_install:
  - gem install bundler -v 2.0.1
  - unset _JAVA_OPTIONS
  - pip install --user xml2rfc

matrix:
  allow_failures:
    - rvm: ruby-head
