version: '{build}'

cache:
  - vendor/bundle

environment:
  matrix:
    - RUBY_VERSION: 25
    - RUBY_VERSION: 24
    - RUBY_VERSION: _trunk

matrix:
  allow_failures:
    - RUBY_VERSION: _trunk

install:
  - ps: . { iwr -useb https://raw.githubusercontent.com/metanorma/metanorma-build-scripts/master/appveyor.ps1 } | iex
  - refreshenv

build_script:
  - set PYTHON_VERSION=37
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%USERPROFILE%\AppData\Roaming\Python\Python%PYTHON_VERSION%\Scripts;C:\Python%PYTHON_VERSION%\Scripts;C:\Python%PYTHON_VERSION%;%PATH%
  - pip3 install --user --upgrade pip
  - pip3 install --user xml2rfc
  - bundle config --local path vendor/bundle
  - bundle update
  - bundle install

before_test:
  - ruby -v
  - gem -v
  - bundle -v

test_script:
  - bundle exec rake